---
title: Zac Heisey | AEC Web Design & Digital Marketing
collections:
  posts:
    title: Posts
    output: true
  projects:
    title: Projects
    output: false
defaults:
- scope:
    path: ''
    type: posts
  values:
    categories: blog
    permalink: "/:categories/:title"
    description: ''
    layout: post
    author: 'Zac Heisey'
- scope:
    path: ''
    type: pages
  values:
    layout: page
    description: ''
- scope:
    path: ''
    type: projects
  values:
    url: ''
    services: ''
    mockup: ''
    case-study: ''
url: "" # the base hostname & protocol for your site, e.g. http://example.com
email: zheisey@gmail.com
description: I'm a digital marketing consultant based in Baltimore, MD. I develop effective digital strategies for home construction, remodeling, and AEC companies.
permalinks: pretty
include:
- _redirects

# Build settings
markdown: kramdown
