---
title: AEC Web Design & Digital Marketing | Zac Heisey
collections:
  posts:
    title: Posts
    output: true
  projects:
    title: Projects
    output: true
defaults: # see admin/config.yml file for Netlify CMS front matter defaults
- scope:
    path: ''
    type: posts
  values:
    categories: blog
    permalink: "/:categories/:title"
    layout: post
    author: 'Zac Heisey'
- scope:
    path: ''
    type: pages
  values:
    layout: page
- scope:
    path: ''
    type: projects
  values:
    layout: project
url: https://www.zac-heisey.com # the base hostname & protocol for your site, e.g. http://example.com
email: zheisey@gmail.com
description: I'm a digital marketing consultant based in Baltimore, MD. I develop effective digital strategies for home construction, remodeling, and AEC companies.
permalink: pretty
include:
- _redirects
plugins:
- jekyll-sitemap

#Build Settings
markdown: kramdown
