---
title: Freelance Web Design & Development for Nonprofits | Zac Heisey
collections:
  posts:
    title: Posts
    output: true
  lessons:
    title: Lessons
    output: true
    permalink: "/web-dev-101/:path/"
defaults: # see admin/config.yml file for Netlify CMS front matter defaults
- scope:
    path: ''
    type: posts
  values:
    categories: blog
    permalink: "/:categories/:title"
    layout: post
- scope:
    path: ''
    type: pages
  values:
    layout: page
- scope:
    path: ''
    type: lessons
  values:
    layout: lesson
url: https://www.zac-heisey.com # the base hostname & protocol for your site, e.g. http://example.com
email: zheisey@gmail.com
description: I'm a freelance web developer in Baltimore, MD. I help nonprofits and social impact organizations with digital strategy, web design, and web development.
permalink: pretty
include:
- _redirects
plugins:
- jekyll-sitemap

#Build Settings
markdown: kramdown

kramdown:
  auto_ids: false
