---
title: Freelance Web Developer & Instructor
collections:
  posts:
    title: Posts
    output: true
  courses:
    title: Courses
    output: true
    permalink: "/web-dev-101/:path/"
defaults: # see admin/config.yml file for Netlify CMS front matter defaults
- scope:
    path: ''
    type: posts
  values:
    categories: blog
    permalink: "/:categories/:title"
    layout: post
- scope:
    path: ''
    type: pages
  values:
    layout: page
- scope:
    path: ''
    type: courses
  values:
    layout: course
url: https://www.zac-heisey.com # the base hostname & protocol for your site, e.g. http://example.com
email: zheisey@gmail.com
description: I'm a freelance web developer and instructor with a passion for vanilla JavaScript, nonprofits, teaching, travel, and JAMstack web development.
permalink: pretty
include:
- _redirects
plugins:
- jekyll-sitemap

#Build Settings
markdown: kramdown

kramdown:
  auto_ids: false
