---
title: Zac Heisey | Home Improvement Web Consulting & Digital Marketing
collections:
  posts:
    title: Posts
    output: true
defaults:
- scope:
    path: ''
    type: posts
  values:
    categories: blog
    permalink: "/:categories/:title"
    description: ''
    layout: post
    author: 'Zac Heisey'
- scope:
    path: ''
    type: pages
  values:
    layout: page
    description: ''

url: "" # the base hostname & protocol for your site, e.g. http://example.com
email: zheisey@gmail.com
description: I'm a web consultant based in Baltimore, MD. I help home improvement and AEC companies craft effective digital marketing strategies to further their cause online.
permalinks: pretty
include:
- _redirects

# Build settings
markdown: kramdown
