---
title: Digital Marketing & Online Advertising | Zac Heisey
collections:
  posts:
    title: Posts
    output: true
defaults: # see admin/config.yml file for Netlify CMS front matter defaults
- scope:
    path: ''
    type: posts
  values:
    categories: blog
    permalink: "/:categories/:title"
    layout: post
- scope:
    path: ''
    type: pages
  values:
    layout: page
url: https://www.zac-heisey.com # the base hostname & protocol for your site, e.g. http://example.com
email: zheisey@gmail.com
description: I'm a digital marketing consultant with 10+ years of online advertising experience. I build online ad campaigns that drive more traffic, leads, sales, and growth.
permalink: pretty
include:
- _redirects
plugins:
- jekyll-sitemap

#Build Settings
markdown: kramdown
