---
title: Freelance Web Design & Development | Zac Heisey
collections:
  posts:
    title: Posts
    output: true
defaults: # see admin/config.yml file for Netlify CMS front matter defaults
- scope:
    path: ''
    type: posts
  values:
    categories: blog
    permalink: "/:categories/:title"
    layout: post
- scope:
    path: ''
    type: pages
  values:
    layout: page
url: https://www.zac-heisey.com # the base hostname & protocol for your site, e.g. http://example.com
email: zheisey@gmail.com
description: I'm a freelance web designer with 10+ years of digital industry experience. I build clean, simple websites for startups, small businesses, and nonprofit organizations using Jekyll and Hugo.
permalink: pretty
include:
- _redirects
plugins:
- jekyll-sitemap

#Build Settings
markdown: kramdown
